### ISSUE TITLE
Not transpilable code

### ISSUE THREAD

**Issue by belvederef** [vtimofeev/vue-check-view#2]
This module gives problems with IE11 due to its use of ES6 features. It should be made retro-compatible with older ES versions.

**Comment by vtimofeev** [comment]
Hi. The library don't uses ES6, only ES5. But the example written with ES6.

**Comment by coreycoburn** [comment]
This issue should be opened back up. The library isn't only written in ES5. This package uses `Object.assign`, `const` and `let`. IE and older browsers will throw errors with this package.

**Comment by coreycoburn** [comment]
Also, a default value can't set as function args.,  arrow functions, array destructuring, object property shorthand...

**Comment by coreycoburn** [comment]
I just created a pull request to resolve this issue.

**Comment by coreycoburn** [comment]
@vtimofeev Thanks for this great package!
