### ISSUE TITLE
this is brilliant! but can use from mounted() hook? 

### ISSUE THREAD

**Issue by simonhrogers** [vtimofeev/vue-check-view#4]
It would be great if it were possible to check `e.percentInView` on page load – I need to apply a class if `e.percentInView > 0.98` on page load as the view-in--full is not always accurate initially.

**Comment by vtimofeev** [comment]
Hello, has no direct method to do it. 
But you can use:
```
window.dispatchEvent(new Event('scroll')) -> it's call internal handler and positions'll be rechecked
```
